[install]
lockfile = true
no-save-workspace-prefix = true
minimumReleaseAge = 2592000
minimumReleaseAgeExcludes = ["@types/bun", "bun-types", "msgpackr"]

[test]
preload = ["./test/setup.ts"]

[serve.static]
plugins = []
