[install]
lockfile = true
no-save-workspace-prefix = true
minimumReleaseAge = 2592000
minimumReleaseAgeExcludes = ["@types/bun", "bun-types", "msgpackr", "effect", "@effect/platform", "@effect/platform-bun", "@effect/platform-node-shared", "@effect/cluster", "@effect/rpc", "@effect/sql"]

[test]
preload = ["./test/setup.ts"]

[serve.static]
plugins = []
